image: gitpod/workspace

tasks:
  - name: Install dependencies
    command: |
      apk update
      apk add curl wget tar
      pip install --upgrade pip
      pip install -r requirements.txt
  - name: Run command
    command: |
      CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
      wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_arm64.tar.gz -O - | tar -xzv -C ~/.local/bin
      chmod u+x ~/.local/bin/saml2aws
      hash -r
      saml2aws --version